language: node_js
node_js:
  - "0.10"
  - "0.12"
  - "4"
  - "5"
before_install:
  - sudo apt-get -y install libicu-dev
  - npm install -g npm
script:
  - "npm run-script start"
notifications:
  irc: "irc.rizon.net##sorairo-subs"
